<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>wplace_canYouHelpMe</AssemblyName>
    <RootNamespace>wplace_canYouHelpMe</RootNamespace>
  </PropertyGroup>

</Project>
