<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>wplace_canYouHelpMe</AssemblyName>
    <RootNamespace>wplace_canYouHelpMe</RootNamespace>
    <Version>1.0.1</Version>
    <FileVersion>1.0.1.0</FileVersion>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

</Project>
